# Generated by Django 4.2.7 on 2023-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_bid_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("", "Select a category"),
                    ("1", "Bedroom"),
                    ("2", "Living Room"),
                    ("3", "Kitchen"),
                    ("4", "Office"),
                    ("5", "Dining Room"),
                    ("6", "Entertainment"),
                    ("7", "Outdoor"),
                    ("8", "Bathroom"),
                    ("9", "Sports"),
                    ("10", "Auto"),
                    ("11", "Electronics"),
                    ("12", "Clothing"),
                    ("13", "Beauty"),
                    ("14", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
