# Generated by Django 4.2.7 on 2023-11-09 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing_comments_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thebid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
