# Generated by Django 4.2.7 on 2023-11-11 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_bid_item_comments_item_alter_bid_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bid",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
